config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/', to: 'site#home'
get 'contact', to: 'site#contact'

get '/calculator', to: 'site#calculator'
post '/calculate', to: 'site#calculate'

#get '/projects', to: 'projects#index'
#get 'projects/new', to: 'projects#new'

#get '/projects/:id', to: 'projects#show' #tenemos que poner las rutas por encima para que no confunda con parametros

#post '/projects', to: 'projects#create' #lo podemos poner debajo porqué es un post
resources :projects, only: [:index, :show, :new, :create] do #nos sustituye todas las rutas projects
	resources :time_entries, except: [:show] #nos sustiture todas las rutas time_entries asociadas a projects
end

#get '/projects/:project_id/time_entries', to: 'time_entries#index'
#get '/projects/:project_id/time_entries/new', to: 'time_entries#new'
#post '/projects/:project_id/time_entries', to: 'time_entries#create', as: :project_time_entries

#get '/projects/:project_id/time_entries/:id/edit', to: 'time_entries#edit'
#patch '/projects/:project_id/time_entries/:id', to: 'time_entries#update', as: :project_time_entry #patch para editar

#delete '/projects/:project_id/time_entries/:id', to: 'time_entries#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :time_entries
	
	def self.clean_old(date = 1.week.ago)
		where('created_at < ?', date).destroy_all
	end
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
	belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.order(created_at: :desc).limit(10)
	end

	def show
		@project = Project.find_by(id: params[:id])
		unless @project
			render 'no_projects_found'
		end
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(
			:name => params[:project][:name],
			:description => params[:project][:description])
		@project.save

		redirect_to "/projects/#{@project.id}" #con comillas dobles interpreta el valor de la variable, con simples no
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		#render 'home' // si la vista se llama igual que el def podemos ahorrarnos esta linea
	end

	def contact
	end

	def calculator
	end

	def calculate
		@num1 = params[:first_num].to_f
		@num2 = params[:second_num].to_f
		@result = @num1 + @num2
	end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	
	def index
		@project = Project.find(params[:project_id])
		@entries = @project.time_entries.where('date > ?' , 1.month.ago.end_of_month)
	end

	def new
		@project = Project.find(params[:project_id])
		@entry = @project.time_entries.new
	end

	def create
		@project = Project.find(params[:project_id])
		@entry = @project.time_entries.new(entry_params)
		
		if @entry.save
			redirect_to "/projects/#{@project.id}/time_entries"
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find(params[:project_id])
		@entry = @project.time_entries.find(params[:id])
	end

	def update
		@project = Project.find_by(id: params[:project_id])
		@entry = @project.time_entries.find_by(id: params[:id])

		if @entry.update(entry_params)
			redirect_to "/projects/#{@project.id}/time_entries"
		else
			render 'edit'
		end
	end

	def destroy
		@project = Project.find_by(id: params[:project_id])
		@entry = @project.time_entries.find_by(id: params[:id])
		
		@entry.destroy #no es obligatorio el if en destroy
		redirect_to action: :index, project_id: @project.id 
	end

	private

	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date)
		# (entry_params) nos substituirá:
		#(hours: params[:time_entry][:hours],
		#minutes: params[:time_entry][:minutes],
		#date: params[:time_entry][:date])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
<% @projects.each do |project| %>
	<li>
		<%= project.name %>
		<% if project.description.present? %> <!-- si no tiene descripción (sea nil o string vacío) no la pone -->
		- <%= project.description %>
		<% end %>
	</li>
<% end %>
</ul>

app/views/projects/new.html.erb
<h1>Add a project</h1>
<%= form_for @project do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<p><%= f.label :description %>
	<%= f.text_area :description %></p>
	<p><%= f.button %></p>
<% end %>

app/views/projects/no_projects_found.html.erb
<h1>Sorry, project not found</h1>

app/views/projects/show.html.erb
<h1>My project <%= @project.id %> </h1>
<%= @project.name %> 
<% if @project.description.present? %>
	- <%= @project.description %>
<% end %>

app/views/site/calculate.html.erb
The result of <%= @num1 %> + <%= @num2 %> is <%= @result %>
<p><%= link_to "Calculator", "/calculator", class: "calculator-link" %></p>

app/views/site/calculator.html.erb
<form action='/calculate' method="POST">
	<input type="text" name="first_num" placeholder="First Number">
	<input type="text" name="second_num" placeholder="Second Number">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<button type="submit">Add</button>
</form>

app/views/site/contact.html.erb
<p>Hola! si quieres contactar con nosotros puedes enviar un mail a contact@example.com</p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>

<p>Ironhack powered</p>

<img src="/assets/dramatic-glasses.gif" alt="Kid removing his sunglasses epically" class='image'>
<%= image_tag "dramatic-glasses.gif", alt:"Kid removing his sunglasses epically", class:'image' %>

<p><%= link_to "Calculator", "/calculator", class: "calculator-link" %></p>
<p><%= link_to "Contact", "/contact", class: "contact-link" %></p>
<p><%= link_to "Projects", "/projects" %></p>

app/views/time_entries/_form.html.erb
<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg| %>
		<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_for [@project, @entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>

	<%= f.button %>
<%= link_to 'Cancel', project_time_entries_path(@project) %>
<% end %>

app/views/time_entries/edit.html.erb
<h2>Edit time entry for <%= @project.name %></h2>
<%= render "form" %><!-- nos envía a la vista form donde tenemos el formulario para no repetirlo-->

app/views/time_entries/index.html.erb
<h1>Time Tracking tool</h1>
<h2><%= @project.name %></h2>
<% @entries.each do |entry| %>
	<li>
		<%= entry.hours %> h
		<%= entry.minutes %> m -
		<%= entry.date %>
		<%= link_to 'Edit', "/projects/#{@project.id}/time_entries/#{entry.id}/edit" %> -
		<%= link_to('Delete', project_time_entry_path(@project, entry), method: :delete, data: {confirm: 'Are you sure?'}) %>
	</li>
<% end %>
</ul>

app/views/time_entries/new.html.erb
<h2>Creating a new time entry in <%= @project.name %></h2>
<%= render "form" %> <!-- nos envía a la vista form donde tenemos el formulario para no repetirlo-->